### ISSUE TITLE
Breadcrumbs have weird behavior

### ISSUE THREAD

**Issue by ZitaNemeckova** [ManageIQ/miq_v2v_ui_plugin#127]
Compute redirects user to last page under Compute he visited but there's no information which it is.

Migration redirects user to Migration/Overview even when he never visited it.
How to reproduce:
- Log in
- Go to Compute -> Migration -> Infrastructure Mapping
- Click Migration in breadcrumbs

v2v:
<img width="228" alt="screen shot 2018-03-07 at 10 25 09 am" src="https://user-images.githubusercontent.com/9210860/37085238-d6d5aa80-21f4-11e8-9874-5603f690fece.png">

manageiq-ui-classic:
<img width="396" alt="screen shot 2018-03-07 at 10 46 02 am" src="https://user-images.githubusercontent.com/9210860/37085222-c5f12ef6-21f4-11e8-81e4-7aad8da28ceb.png">

But in general it's not consistent:
- named after navigation bar X named after page titles
- Infra provider pages are not mentioned in Cloud provider's breadcrumbs X Migration's Compute points to another page under Compute

**Comment by serenamarie125** [comment]
@ZitaNemeckova from a UX perspective, the breadcrumbs should be location breadcrumbs.  Currently, I don't think that ManageIQ is following that.  We should likely add an issue there to update appropriately.

**Comment by priley86** [comment]
V2V now looks like this (it looks like PF was updated single we are seeing the single arrow now 👍 )...

<img width="175" alt="screen shot 2018-05-18 at 10 28 52 am" src="https://user-images.githubusercontent.com/4237045/40240360-66060c94-5a86-11e8-9ead-d0c0ac1e3d7f.png">
<img width="219" alt="screen shot 2018-05-18 at 10 29 11 am" src="https://user-images.githubusercontent.com/4237045/40240365-67e8c06a-5a86-11e8-9688-bacfb3a0d4ba.png">

Not sure if this can be closed but just noticed it.

**Comment by priley86** [comment]
This is working per the current UX guidelines. Closing this issue for now.
