### ISSUE TITLE
Minor UX edge case when no objects in database

### ISSUE THREAD

**Issue by Fryguy** [ManageIQ/miq_v2v_ui_plugin#163]
I haven't set up a provider yet, thus I don't have any clusters, networks, nor datastores.  However, I'm able to go to the Migration screen and start the wizard, only to get to the cluster page with nothing there.  We should probably prevent access to the wizard, or perhaps the entire migration tab when there are no providers defined.  Or perhaps, more specifically, if there are no providers defined for the migration types we care about.

Does it make sense to even show v2v if there is only 1 provider?  Can the source and destination be on the same provider?  If not, then substitute "no providers" with "less than 2 providers" up above.

**Comment by serenamarie125** [comment]
Great questions @Fryguy 

From a UX perspective, I'm not sure if we should disable them from getting there.

I think we have 2 choices:

1. post an error message when they select "Create Infa Mapping" 
2. show a different empty state pattern stating "Migration is not available unless ..." 

I think I'd suggest # 2 - the thing is that we will have to continue to edit this text as we include additional v2v support.  @vconzola this is a good item to bring up to Brett & Marco

**Comment by vconzola** [comment]
@Fryguy I agree with @serenamarie125 's option number 2 and Marco and Brett are OK with it too. So for now, since we have only one source (VMware) and one target (RHV) provider, we'll change the text in the empty state to inform the user that migration isn't possible if both providers aren't set up yet. @priley86 says the API is already in place to enable this. 

When we start supporting other providers we can restrict what migrations are possible by the options we display for selecting source and target providers in step 1 of the Mapping wizard. 

Thanks for pointing this out.

**Comment by vconzola** [comment]
Mockup for this edge case:
![overview - all empty mappings copy 3 providers not configured - opt2](https://user-images.githubusercontent.com/22823035/38581894-1ab11b84-3cdc-11e8-8fc6-151137f8d873.png)

**Comment by serenamarie125** [comment]
@vconzola i just realized ... is this if there's a missing RHV or VMware provider :O

**Comment by vconzola** [comment]
@serenamarie125 I assume we will link to Compute > Infrastructure > Providers. From there the user can can which providers are configured and add RHV or VMware as necessary.

**Comment by serenamarie125** [comment]
@mturley take this once you're set with 311

**Comment by mturley** [comment]
You got it.

**Comment by mturley** [comment]
#358 will fix this, and has been reviewed, but the build is failing. I'm messing with some unit tests, it'll be merged soon and then this can be closed.

**Comment by serenamarie125** [comment]
> @serenamarie125 did we determine if @vconzola is right, and we'll just link to Compute > Infrastructure > Providers with this new button? Or is there more logic that needs to be done there?

@mturley shoot i never saw that comment .  Did you confirm with @vconzola ?

**Comment by mturley** [comment]
@serenamarie125 I never did, but it seemed to make the most sense to just link there. I assumed he was right and implemented it with just that simple link to that Providers page. (`/ems_cloud/show_list`).  Hmm... actually, shoot, I linked to Cloud > Providers not Infrastructure > Providers. there are three Providers pages... @vconzola can you give any more insight on what this "Configure Providers" button should do?

**Comment by mturley** [comment]
I'll update my PR to link to Infrastructure > Providers (`/ems_infra/show_list`). Seems like that's the right place to find RHV and VMWare.

**Comment by vconzola** [comment]
@mturley Compute > Infrastructure > Providers is where users can go to add providers if they don't exist, so that's where we should link.
