### ISSUE TITLE
Target Clusters Require Configured Conversion Host

### ISSUE THREAD

**Issue by vconzola** [ManageIQ/miq_v2v_ui_plugin#189]
We need to add a warning to any target cluster in step 2 of the infra mapping wizard that doesn't have at least one configured conversion host. We won't stop the user from mapping the cluster, just warn and provide a dismissible popover with more information.
![4aa-createmapping-clusters w datacentre - option 2 w warning](https://user-images.githubusercontent.com/22823035/38520921-25b178dc-3c12-11e8-9e7b-40b4f9d7c938.png)

**Comment by serenamarie125** [comment]
@bthurber tagging you on anything labeled _needs-api_ for awareness

**Comment by vconzola** [comment]
@bthurber This one's been sitting in our backlog for a while. Any idea if any work has been done on the backend to identify which clusters have configured migration hosts? If you're not sure we can discuss in our sync meeting tomorrow.

**Comment by bthurber** [comment]
@vconzola we are tracking in a Trello card on our board for this sprint.  It has a link to meeting notes I would recommend reviewing.  We can discuss tomorrow as well.

**Comment by bthurber** [comment]
@vconzola https://bugzilla.redhat.com/show_bug.cgi?id=1571778

**Comment by vconzola** [comment]
@bthurber Is this something we need for GA?

**Comment by bthurber** [comment]
@vconzola nice to have for GA.  If not possible in time then will push to 5.9.5 or 5.10.

**Comment by bdunne** [comment]
It looks like tags are already visible as a sub-collection on hosts and clusters.  What are the missing pieces?

**Comment by bthurber** [comment]
@bdunne plan has changed slightly.  Sent over new plan.

**Comment by mturley** [comment]
Starting on the UI piece of this next (first thing Monday). @bthurber do we know what the API will look like for this yet / have a PR I can follow for that yet? If not that's ok, I can start working top-down.

**Comment by bthurber** [comment]
@mturley not sure but I would touch base with @bdunne
