### ISSUE TITLE
Add Hound integration

### ISSUE THREAD

**Issue by priley86** [ManageIQ/miq_v2v_ui_plugin#20]
* Travis now runs our jest tests/eslint. In this issue we will integrate Hound CI for linting.
https://github.com/ManageIQ/miq_bot/issues/368

**Comment by ZitaNemeckova** [comment]
Hound integration for ManageIQ is discussed [here](https://github.com/ManageIQ/miq_bot/issues/368). So maybe we can wait with it until some decision is made.

**Comment by AllenBW** [comment]
@priley86 I'm fine with closing this.... likely couldn't be done till the repo rename anyways
