### ISSUE TITLE
Display error in the VMs table when duplicate VMs are found in the CSV file or VMs in the CSV file don't exist on the source clusters

### ISSUE THREAD

**Issue by vconzola** [ManageIQ/miq_v2v_ui_plugin#207]
In step 2 of the Plans wizard, if the user selects to import a list of VMs from a CSV file the contents of the file will be validated by the backend and any duplicate VM names or VM names not found on the source clusters will be tagged. The UI needs to call out these VMs in the VMs table and inform the user.
![9c3-createplan-vms-import selection duplicates - opt1](https://user-images.githubusercontent.com/22823035/38739292-78845208-3f02-11e8-8c75-44da2af5e252.png)

The tooltip text should be:
"VM has the same name as another VM on the same cluster. You must edit the .CSV file to resolve the name duplication before you can add the VM to a migration plan."  <-- FOR DUPLICATES
"VM does not exist on the source cluster, so it cannot be added to a migration plan." <-- FOR VMs NOT FOUND
"VM ready for migration." <-- FOR VMs that are OK.

Rows with errors are disabled so the VMs can not be selected for the migration plan.

**Comment by kedark3** [comment]
![screenshot from 2018-05-22 10-33-13](https://user-images.githubusercontent.com/8180469/40369291-98d6706e-5dab-11e8-9c7f-efeb34d2fc20.png)
I can see duplicate VMs available for migration, both of them. Should throw error/warning.

**Comment by JPrause** [comment]
@miq-bot add_label blocker

**Comment by AllenBW** [comment]
(no idea why it ignored yah @JPrause 😭)

@Fryguy any reason why miq- 🤖 might be ignoring *commands* here?  (was thinkin... newly minted repo... maybe? )
