### ISSUE TITLE
When looking at migration plan details, a "download log" link should be available for each VM

### ISSUE THREAD

**Issue by serenamarie125** [ManageIQ/miq_v2v_ui_plugin#208]
When drilling into a Migration Plan, the UI shows each VM.  This issue captures the need to add a "Download Log" link for each VM entry.

There is an API dependency here.

**Comment by serenamarie125** [comment]
@bthurber tagging you on anything labeled _needs-api_ for awareness

**Comment by vconzola** [comment]
![11a-plan details as list in drill down w download](https://user-images.githubusercontent.com/22823035/38813016-d289e1cc-415b-11e8-8586-142b8cfdf4a1.png)

**Comment by serenamarie125** [comment]
@vconzola 

- what icon is shown? fa-download
- Is this link only added once the migration is complete?
- Should we specific tooltip text
- What is the link text ... "Download log", "Log File", "Download Log", "Log file"?

**Comment by vconzola** [comment]
@serenamarie125 
- Talked to Jenny H. She said fa-download is already in PF because it's part of Font Awesome 4.7. [](https://fontawesome.com/v4.7.0/icon/download/).
- Bill W. and Greg say that download file will be available as soon as the migration is started, so link should be added as soon as migration becomes active.
- Don't think we need tooltip text unless it's required for accessibility.
- The link text should be "Log file". It's shorter and I think of this as a Prompt which uses sentence capitalization.

**Comment by serenamarie125** [comment]
@vconzola just checked T&W section of PatternFly for [Links](http://www.patternfly.org/styles/terminology-and-wording/#links).  After reaching that, I'd suggest the link label be "Download log".  Please take a look and see what you think!

**Comment by serenamarie125** [comment]
Once we come to an agreement, can you update the mock here ?

**Comment by vconzola** [comment]
Updated mockup.
![11a-plan details as list in drill down w download](https://user-images.githubusercontent.com/22823035/39000230-78f6e9f8-43c1-11e8-8a7e-23e95b13aebb.png)

**Comment by priley86** [comment]
@bzwei @AparnaKarve can you provide any API update on the download log function?

**Comment by bzwei** [comment]
There is no API for it. @AparnaKarve and I discussed, and we should have a controller to support file download.

**Comment by mturley** [comment]
@serenamarie125 do we want to hold off working on the UI for this until the API is ready? Or should one of us grab this and get it started?

**Comment by AparnaKarve** [comment]
@bthurber An update on the progress here -

The backend code (Rails controller that calls the backend method) is done. 
@priley86 and I will try and put the remaining implementation together today.
This may be touch-and-go for sprint7, but we will give our best shot.

Also, I need to do a basic sanity check with the existing code and need a real v2v environment -- so I was wondering if I could use the miqnightlynewui appliance if it's still available?
Thanks.

**Comment by bthurber** [comment]
@AparnaKarve yes please feel free to.

**Comment by priley86** [comment]
it looks like we forgot to close this when merging #309 .
