### ISSUE TITLE
Plan Wizard - consistent headings

### ISSUE THREAD

**Issue by priley86** [ManageIQ/miq_v2v_ui_plugin#242]
Is it just me or are these headings different now? The designer in me would love to make them consistent...
![screen shot 2018-04-24 at 8 49 15 am](https://user-images.githubusercontent.com/4237045/39187959-a1a49966-479c-11e8-8f7f-d6e77d3c07c4.png)

![screen shot 2018-04-24 at 8 49 04 am](https://user-images.githubusercontent.com/4237045/39187945-975b4bd0-479c-11e8-9c4e-9934f953313b.png)

**Comment by serenamarie125** [comment]
@priley86 I'm not following.  What's inconsistent here ?

**Comment by priley86** [comment]
@serenamarie125 do we typically put captions/labels above radio buttons like that or do we use headings? It seems like "Run migration plan" on Step 3 is a label...but we have no heading on that step and it just seems inconsistent to me w/ Step 2. Or maybe - to preserve space on Step 2 we just use a label and it's then consistent?

just figured i would point this out and ask ;-)

**Comment by priley86** [comment]
Closing this - it is not a pressing concern and the design is already planned to change.
