### ISSUE TITLE
Infra Mapping Wizard show irrelevant RHV clusters

### ISSUE THREAD

**Issue by istein1** [ManageIQ/miq_v2v_ui_plugin#251]
There are cases that the RHV clusters might be irrelevant, for example when the hosts, residing on the clusters are not set as conversion hosts - which will eventually fail the migration.
In such cases, it would be better to filter those clusters 
(and RHV data centers too, once those will be added to the mapping wizard).  

Version-Release:
master.20180417121918_2dd64f8

BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1571778

**Comment by vconzola** [comment]
@istein1 We are working on a UI update that will notify users when a RHV cluster does not contain a conversion host, but we were instructed by PM not to block selection of those clusters because conversion host setup can be done after mapping but before migration plan execution.

**Comment by istein1** [comment]
@vconzola , 
I see. Thank for the detailed explanation. 
May I suggest those 2 alternatives:
1. To have the hosts missing conversion part to be marked with an asterisk, 
and mention bellow those hosts are missing conversion setting.
2. Add a warning to the user, before submitting the migration plan execution, 
that there are RHV hosts that are not conversion hosts - 
This way the user will not waste time by running it, wait a long time, and eventually have migration fail, while it could have been avoided from the beginning, by a simple validation.

What do you think?

**Comment by vconzola** [comment]
@istein1 Here's a mockup of what we're planning to show in the mappings wizard for clusters without conversion hosts configured. We'll add a similar warning before migration. I just haven't mocked that one up yet.
![4aa-createmapping-clusters w datacentre - option 2 w warning](https://user-images.githubusercontent.com/22823035/39309111-36cdb506-4935-11e8-833f-1328a1ff8148.png)

**Comment by istein1** [comment]
@vconzola That looks great, thanks.

**Comment by vconzola** [comment]
Related to #189

**Comment by bthurber** [comment]
@vconzola ok to close or change to merged?

**Comment by vconzola** [comment]
Fixed by #526
