### ISSUE TITLE
Multiple networks with the same name appear for target provider for infrastructure mappings

### ISSUE THREAD

**Issue by bthurber** [ManageIQ/miq_v2v_ui_plugin#257]
BZ:  https://bugzilla.redhat.com/show_bug.cgi?id=1572169

Example:  ovirtmgmt for a single target appears twice.  2 hosts enabled for the RHV provider with the conversion host role.

**Comment by bthurber** [comment]
@priley86 @AparnaKarve this looks like a similar issue is having in his Ravello env.  I think our solution here is going to be the same as for source networks...filter duplicate names in the UI.

**Comment by bthurber** [comment]
![screenshot from 2018-05-23 23-06-35](https://user-images.githubusercontent.com/4692674/40463983-f87792ea-5edd-11e8-8151-fd128900e97a.png)

**Comment by priley86** [comment]
@AparnaKarve is looking into this and will pull in the database from that environment...

**Comment by JPrause** [comment]
@miq-bot add_label blocker

**Comment by JPrause** [comment]
@AparnaKarve did you have an update on this PR.

**Comment by AparnaKarve** [comment]
@JPrause I don't, atm.

We are currently waiting on a specific input from the RHV team regarding the Network deduplication. 
Once @agrare hears back from them, we will have a plan on how to proceed on this.
Thanks.

**Comment by agrare** [comment]
@AparnaKarve I confirmed with RHV that uid_ems can be used to unique lans.

**Comment by AparnaKarve** [comment]
Thanks @agrare !
Since most of our discussion on this topic is in #281, I have a comment there and just need you to confirm the mapping structure https://github.com/ManageIQ/miq_v2v_ui_plugin/issues/281#issuecomment-399122472

**Comment by priley86** [comment]
Cool - we are using `uid_ems` to dedupe networks in the [Infra Mapping list view](https://github.com/ManageIQ/miq_v2v_ui_plugin/blob/master/app/javascript/react/screens/App/Overview/components/InfrastructureMappingsList/helpers.js#L160) as well already so it sounds like merging #404 will resolve this once and for all...

**Comment by JPrause** [comment]
Any update on this PR. We have an upcoming build on July 10

**Comment by priley86** [comment]
I believe this issue can be closed now. We are using the `uid_ems` to uniquely identify lans now, however to fully qualify this, we should also include the provider & cluster when uniquely identifying. If these aren't included, we risk a small edge case mentioned in [#455](https://github.com/ManageIQ/miq_v2v_ui_plugin/issues/455). I'm looking at this currently.
