### ISSUE TITLE
Migration fails if the VM name is too long 

### ISSUE THREAD

**Issue by bthurber** [ManageIQ/miq_v2v_ui_plugin#258]
BZ reference:  https://bugzilla.redhat.com/show_bug.cgi?id=1571963

**Comment by AllenBW** [comment]
@vconzola you ok with a solution of truncating overflow with ellipses and throw up a tooltip with the rest of the name?  (thing we did in that other place)

**Comment by priley86** [comment]
@AllenBW does VM Name wrap as well? Not sure if this relates to #259

**Comment by AllenBW** [comment]
@bzwei any thoughts on the log results? (posting from the bz) 

![screenshot from 2018-04-25 15-31-01 1](https://user-images.githubusercontent.com/6640236/39533616-844e6754-4dfd-11e8-8384-116ef4653845.png)

**Comment by AllenBW** [comment]
Naaaah I'm not the right one to assign to this...

**Comment by priley86** [comment]
ok seems to be a backend issue after discussing some more w/ @vconzola and looking at this... thanks @AllenBW . i'm in favor of deferring this one to sprint8 - it seems we have other things we need to consider (i.e. VMWare name length not matching RHEV name length which may not match MIQ name length).

@vconzola @serenamarie125 can you follow up w/ @bthurber on this before we implement anything in the UI next sprint?

**Comment by bthurber** [comment]
OK to move to Sprint 8

**Comment by bzwei** [comment]
@AllenBW The error comes from OvirtSDK. It is a back-back-end problem. If ovirt has length constraint for VM name, that's the limitation we should follow.

**Comment by bthurber** [comment]
@AllenBW please ask kk to file a BZ for RHV on this.

**Comment by AllenBW** [comment]
Keeping this bz alive and flagging it as wont fix, (rationale is.. this isn't something we'll fix, but we need to track cuzzzzz it matters)

**Comment by JPrause** [comment]
This is a blocker for https://bugzilla.redhat.com/show_bug.cgi?id=1571963

**Comment by vconzola** [comment]
@bthurber @JPrause  I don't think this is a UI issue. From the comments above it looks like it needs to be fixed in RHV. Can we close the issue here?

**Comment by bthurber** [comment]
@vconzola 10-4.  Will move to RHV team.  Not a blocker for 5.9.3

**Comment by bthurber** [comment]
Downstream BZ is closed for this.  Will address in the future if needed.
