### ISSUE TITLE
Source-target cluster mappings should be identifiable in the infrastructure mappings expanded list view

### ISSUE THREAD

**Issue by vconzola** [ManageIQ/miq_v2v_ui_plugin#277]
When an infrastructure mapping is expanded in the list view, the source-target mappings should be easily identifiable. This can be done through custom line spacing (short term) of the cluster lists or through another another visualization technique (TBD) long term. The custom line spacing option is shown here:
![overview - w mappings mappings copy 3 1 mapping w_ list expansion](https://user-images.githubusercontent.com/22823035/39485933-67e11766-4d48-11e8-89d5-904e980a546b.png)

**Comment by priley86** [comment]
this is being redesigned/reworked currently in #310 . Closing...
