### ISSUE TITLE
User should be able to see associated migration plans for an infrastructure mapping

### ISSUE THREAD

**Issue by vconzola** [ManageIQ/miq_v2v_ui_plugin#278]
In the infrastructure mapping list view expansion the user should be able to see a list of migration plans associated with the mapping.
![overview - w mappings mappings copy 3 1 mapping w_ list expansion](https://user-images.githubusercontent.com/22823035/39486130-1659df1c-4d49-11e8-914f-8101bd7a0743.png)

**Comment by priley86** [comment]
Duplicate of #321 which i am currently working - closing.
