### ISSUE TITLE
Currently only the CSV import will let you view and select an already migrated VM — the discovery process does not

### ISSUE THREAD

**Issue by kedark3** [ManageIQ/miq_v2v_ui_plugin#293]
@bzwei @AparnaKarve 
https://bugzilla.redhat.com/show_bug.cgi?id=1575109

**Comment by priley86** [comment]
per discussion this morning in gitter, this will require a backend change first.

**Comment by AparnaKarve** [comment]
In fact, this will be a 100% backend change.

In the CSV mode, the UI already has the support to let the user select "once-migrated" VMs.
Once the backend is adjusted for the discovery process, to output both valid and invalid VMs, the UI should just work.

/cc @bzwei

**Comment by serenamarie125** [comment]
@blomquisg here's another one!

**Comment by blomquisg** [comment]
I'm not sure I understand.  I read in an email thread that we don't want to support migrating already migrated VMs.

**Comment by AparnaKarve** [comment]
@bthurber Is this still a requirement -- to discover VMs that have already been migrated?

**Comment by bthurber** [comment]
@AparnaKarve I believe we are OK with the workaround with .csv import.  OK to close.

**Comment by serenamarie125** [comment]
Closing per Brett’s confirmation that we are good
