### ISSUE TITLE
Users need to be able to delete infrastructure mappings

### ISSUE THREAD

**Issue by serenamarie125** [ManageIQ/miq_v2v_ui_plugin#297]
Users need to be able to delete infrastructure mappings

BEFORE STARTING WORK - need to find out the following:
- what restrictions are there around deleting an infrastructure mapping?
- need a design for this from @vconzola showing 1) where will delete action be available 
2) Text for  delete confirmation
3) what if you are trying to delete something that cannot be delete, how do we information the user? 
4) what if the deletion is unsuccessful, how do we deal with that ?

API support already exists.  Ping Bill Wei with any questions.

**Comment by priley86** [comment]
should we also include design for deleting plans as well? It seems we have API support for both deleting plans and mappings, but nothing wired up in the UI for this.

**Comment by serenamarie125** [comment]
@AparnaKarve mentioned that her PR for the supporting API was merged yesterday, so removing the needs-api label as well

**Comment by priley86** [comment]
merged in #356. closing
