### ISSUE TITLE
Provide migration error reporting at the plan level

### ISSUE THREAD

**Issue by serenamarie125** [ManageIQ/miq_v2v_ui_plugin#299]
Migration Plans with any aggregated failures currently show an error status.  We should provide a popover, accessible by clicking this error icon, including a high level message noting how many vms have failed at that point

@priley86 do we need an API for this, or do we already have support?
FYI @vconzola

**Comment by priley86** [comment]
hey @serenamarie125 @vconzola - i believe we can already digest the current API queries to determine how many VMs have failed. I am happy to take a look at this one once we are comfortable w/ the design. It seems pretty straight forward so I will start gettting the logic ready now.

**Comment by vconzola** [comment]
Here you go @priley86 . Knock yourself out.
![overview - w all copy 4 filter is in progress w popover](https://user-images.githubusercontent.com/22823035/40129527-79bc4102-5902-11e8-9ab5-3078fdd50672.png)
