### ISSUE TITLE
User should be able to archive a Migration Plan

### ISSUE THREAD

**Issue by serenamarie125** [ManageIQ/miq_v2v_ui_plugin#314]
User should have access to archive a migration plan.  If a migration plan is running, the option should not be available ( should be disabled ).

We should provide a confirmation for archive - thus, the user clicks on the Archive action, but is presented with an confirmation dialog with "Cancel" and "Archive" buttons

**Comment by serenamarie125** [comment]
@AparnaKarve can you confirm if we need API for this?  I was a bit confused during yesterday's meeting.  I'm adding the tag for now ...

**Comment by serenamarie125** [comment]
@vconzola I'm suggesting that we do have a confirmation dialog for this archive action.  Do you agree ?

**Comment by serenamarie125** [comment]
@blomquisg re: API which will archive a migration plan, do we need a sync meeting on this, or are you guys in progress?

**Comment by serenamarie125** [comment]
@vconzola any update on design?

**Comment by vconzola** [comment]
@serenamarie125 Nope.

**Comment by vconzola** [comment]
@serenamarie125 Here's a link to the mockups.

**Comment by serenamarie125** [comment]
Looks like these are the associated API PRs:
https://github.com/ManageIQ/manageiq-schema/issues/207
https://github.com/ManageIQ/manageiq/issues/17480

According to Adam, you can run with those PRs applied locally (he doesn't expect to have to make major changes)

**Comment by agrare** [comment]
PR to manageiq-api https://github.com/ManageIQ/manageiq-api/pull/389

**Comment by michaelkro** [comment]
Also, how would we like to handle if archiving fails?  Error 🥖?

**Comment by agrare** [comment]
API change is in
