### ISSUE TITLE
View Archived Migration Plans from the main Migration page 

### ISSUE THREAD

**Issue by serenamarie125** [ManageIQ/miq_v2v_ui_plugin#315]
User should be able to view archived migration plans.  This means that we need to allow for a filter for the "Archived" state which will show these plans in a list view.

**Comment by serenamarie125** [comment]
@AparnaKarve can you check if there's an API to get all Migration Plans that are "archived"?  If available, please remove the label.  Thanks!

**Comment by AparnaKarve** [comment]
@serenamarie125 This will need both backend and API changes.
So the `needs-api` label is indeed applicable.

**Comment by serenamarie125** [comment]
@blomquisg re: get all Migration Plans that are "archived"
Aparna mentioned that we definitely need support, just touching base to see if this is in the works, or if we need to meet to make sure we are in agreement on the requirements/dependencies.  lmk!

**Comment by blomquisg** [comment]
@serenamarie125 it's not yet in progress on the back end.  Let's meet about this and #314 to make sure we have the right requirements on the back end.

**Comment by serenamarie125** [comment]
@vconzola can you add mocks?

**Comment by vconzola** [comment]
@serenamarie125 Here's a [link](https://docs.google.com/presentation/d/1cvVq0dKL_rXarz-HnD9mQAdcfMJ438ivjPhYMPpOFM0/edit?usp=sharing) to the mockups.

**Comment by serenamarie125** [comment]
Looks like these are the associated API PRs:
https://github.com/ManageIQ/manageiq-schema/issues/207
https://github.com/ManageIQ/manageiq/issues/17480

According to Adam, you can run with those PRs applied locally (he doesn't expect to have to make major changes)

**Comment by michaelkro** [comment]
Closed by #367
