### ISSUE TITLE
Infrastructure Mapping Network Mapping Enhancement

### ISSUE THREAD

**Issue by bthurber** [ManageIQ/miq_v2v_ui_plugin#319]
I would like to be able to map multiple source networks to multiple target networks.  I.E.

network 1  --  network 1
VM Network -- ovirtmgmt
network 2 -- network 2

Currently I can only to several source to one target.

**Comment by bthurber** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1579022

**Comment by serenamarie125** [comment]
@bthurber is there a target sprint for this ?

**Comment by vconzola** [comment]
@bthurber What you're describing sounds like many-many mapping, but the example you show above isn't that. Many-many would look like:

network1 -- network1
VM Network -- network1
VM Network -- ovirtmgmt
network2 -- ovirtmgmt
network2 -- network2

If we truly need to support many-many network mapping that's a huge change to the infra mapping wizard. All along we've been saying many-1 mappings for clusters, datastores, and networks, so this is a major change of direction.

**Comment by bthurber** [comment]
@vconzola without this change migrations for customer's become less feasible.  @SUmmit we found that when talking to most customer's they have at least 2 networks per VM.  We need to offer a one to one mapping to satisfy their migration requirements.

**Comment by vconzola** [comment]
@bthurber I think we need to talk about this. The requirement is still unclear. 1-1 mappings are supported currently.

**Comment by bthurber** [comment]
@vconzola The issue we have today is we cannot select a 1 to 1 mapping for multiple networks.  We can select multiple source networks but only a single target network.

We need the ability to individually map a source to a target network for multiple networks that the VM may have configured in a single infrastructure mapping.  We can do multiple to single....not multiple to multiple.

**Comment by bthurber** [comment]
After further testing and review this appears to be a PEBKAC issue.  Closing this.
