### ISSUE TITLE
Show associated plans in a infrastructure mapping 

### ISSUE THREAD

**Issue by serenamarie125** [ManageIQ/miq_v2v_ui_plugin#321]
@priley86 @vconzola can you add more detail please :)

**Comment by vconzola** [comment]
Mockup here:

![overview - w mappings mappings copy 3 1 mapping w_ list expansion](https://user-images.githubusercontent.com/22823035/40204775-b5bce972-59f7-11e8-903b-2d0b73bcd328.png)

For now we can add the count in the list view, but I might want to change the expansion depending on what we come up with for issue #310. So we should hold tight on coding that.

@serenamarie125 Do you want to break this issue into two parts - one for adding the count to the list view and one for adding the plan names to the expanded view? Or maybe we can roll the latter into #310?

**Comment by priley86** [comment]
API details for retrieving associated plans can now be found here:
https://gist.github.com/bzwei/4441d1afb3d0297365c1cebd0a87ce88
