### ISSUE TITLE
Migration requests are appearing in My Order of SSUI

### ISSUE THREAD

**Issue by Yadnyawalkya** [ManageIQ/miq_v2v_ui_plugin#341]
**Description**
v2v migration requests are appearing in 'My Order' of SSUI.

![screenshot from 2018-04-06 12-51-05 1](https://user-images.githubusercontent.com/10824880/40387513-96969ebc-5e2a-11e8-9493-2e1d575291bc.png)

**Version-Release**
upstream/master.20180517233405_6f8f0cd 

**Steps to Reproduce**
1. Execute any migration request via Migration Plan
2. Navigate to SSUI, check 'My order' from main navigation

**Actual results**
Migration requests are showing in 'My Order' of SSUI

**Expected results**
Should not appear order request in SSUI since it is not related to services

**Internal tracking**
https://bugzilla.redhat.com/show_bug.cgi?id=1565049

**Comment by JPrause** [comment]
@miq-bot add_label blocker

**Comment by JPrause** [comment]
@Yadnyawalkya who can review this issue so ot can be merged. This is a PR for a blocker issue.

**Comment by himdel** [comment]
The API request SUI is using: `/api/service_orders?expand=resources%2Cservice_requests&limit=20&offset=0&attributes=&filter[]=state%3Dordered&sort_by=placed_at&sort_options=&sort_order=desc`

The class used for transformation requests: `ServiceTemplateTransformationPlanRequest` < `ServiceTemplateProvisionRequest`.

So.. this issue is either:

* (manageiq) `ServiceTemplateTransformationPlanRequest`  should not be inheriting from `ServiceTemplateProvisionRequest`

OR

* (manageiq-api) additional filtering is needed for the `service_orders` collection

OR

* (manageiq-ui-service) additional filters need to be added to the SUI request

**Comment by Yadnyawalkya** [comment]
@AllenBW  checked on latest master, issue is still present there. check more info on internal bugzilla https://bugzilla.redhat.com/show_bug.cgi?id=1565049#c11

**Comment by AllenBW** [comment]
Yep digging into this! Erring on the side of an api thing... though... will report back tomorrow morn...

**Comment by AllenBW** [comment]
Ok digging into this, the attributes sui has to filter on the `service_orders` level include 
```
[
    "created_at",
    "id",
    "name",
    "placed_at",
    "state",
    "tenant_id",
    "updated_at",
    "user_id",
    "user_name"
  ]
```

sadly none of em gives us enough information...
within the `service_requests` subcollection there is an attribute `request_type` which can have a value `transformation_plan` but if my memory serves me.. we can't filter off subcollection attributes? 

@abellotti wondering if you can weigh in here? ☝️ 

SO given the case we can't, sui is gonna have to punt on this one 😭

**Comment by serenamarie125** [comment]
@AllenBW does it make sense for you to take this on?

**Comment by AllenBW** [comment]
@serenamarie125 Would need joint support from API friends for this to be an sui fix... if `api/service_orders` had an attribute of type or some other way to differentiate `transformation_plan` service requests from others... SUI could filter on that, filter out transformation plans

Otherwise I would opt for the above solution by @himdel 

> (manageiq-api) additional filtering is needed for the service_orders collection

💇 🌮

**Comment by serenamarie125** [comment]
@blomquisg can you weigh in here ?  Is this API request something that we can get implemented in the near term?

**Comment by himdel** [comment]
So.. I'm thinking this actually needs core support too..

API can filter on 1:1 relations, but I'm not sure filtering ServiceOrders by the `type`s in their (1:N) `service_requests` sounds likely.

(I mean, even if `?filter[]=service_requests[0].type!=ServiceTemplateTransformationRequest` worked, would that be the right thing to filter entire Service Orders on?)

We may need a type on service orders themselves...

**Comment by gtanzillo** [comment]
Can I get the tl;dr on this one?

Is it that we need to be able to filter out migration requests from the SUI so that only ordered services are shown and we don't have an attribute that we can use?

**Comment by AllenBW** [comment]
@gtanzillo **TL;DR**  yer spot on. the endpoint sui is pullin' on is `api/service_orders/` and while an order might have many requests, we have no way of knowing  if any of em is a migration request... though its unclear if you would have a migration request intermingled with other requests...  anywho yeah on that endopoint we wanta be able to filter out those things with migration requests

available anytime on 👖 for an even more entertaining tl;dr 😏

**Comment by vconzola** [comment]
@AllenBW Any update on this? If it's not a v2v UI issue can it be closed?

**Comment by AllenBW** [comment]
Ahh I have no updates, can't answer that question :-/

**Comment by vconzola** [comment]
@AllenBW I don't think Bill W. is on the project anymore. Would you please follow-up with @gtanzillo and come to a resolution. Thanks.

**Comment by AllenBW** [comment]
@ManageIQ/core hi friends 👋 yer friendly neighborhood v2v ui team needs help here pretty please

**Comment by bzwei** [comment]
Do we really have to hide migration requests under SUI my order? Service order (aka shopping cart) is a concept in SUI. Classic-ui does not have shopping cart. For every request created in classic-ui we automatically create a service order, but it is visible under SUI my order. Shouldn't we hide them too? 

Soon we will support pre/post Ansible playbook in v2v. They will appear under SUI my orders too.

If we really have to hide them we will need some design and implementation to hide all requests that do not go through SUI shopping cart.

**Comment by JPrause** [comment]
Any update on this PR. We have an upcoming build on July 10

**Comment by martinpovolny** [comment]
I suggest that you provide some simple solution for the July 10 release and then work on a systematic fix for the Hammer release.

**Comment by JPrause** [comment]
@martinpovolny just to be clear,..the July 10 date is not the release date, only the 1st dev complete and build. There will be a second build and then a final build.

**Comment by himdel** [comment]
So, I kinda agree with Bill here - the SUI has no nice way of filtering now, and that screen was never limited to shopping cart orders anyway.

So, can the short term solution be: "yes, just expect migrations in My Orders"? 

For the long-term solution, we need ServiceOrder to have type.

**Comment by bthurber** [comment]
@vconzola @priley86 thoughts on resolving this for GA?

**Comment by vconzola** [comment]
@bthurber I don't think this is really a v2v UI issue. @allenbw - please correct me if I'm wrong, and/or provide details.

**Comment by AllenBW** [comment]
@bthurbe the solution for this would be a two-parter, service orders need a type attribute and SUI needs to filter by that type [as @himdel mentioned here ](https://github.com/ManageIQ/miq_v2v_ui_plugin/issues/341#issuecomment-405234756)] 

Neither of these parts can be solved by the v2v ui.

We ought to close this issue and reopen it in the repos that would be doing the work (reffing here) cuz this being open in v2v just keeps breaking everyone's ❤️s  😭

**Comment by vconzola** [comment]
@bthurber  ^^

**Comment by bthurber** [comment]
@AllenBW 10-4.  Would you mind creating the new issue and referencing this?  We can tag @blomquisg in it for visibility.  Probably won't get this in for 5.9.4.

**Comment by AllenBW** [comment]
https://github.com/ManageIQ/manageiq/issues/17752

&

https://github.com/ManageIQ/manageiq-ui-service/issues/1463

means we can close this one here!  ☺️
