### ISSUE TITLE
Add the migration plan status icon in the breadcrumbs in Migration Plan Details page

### ISSUE THREAD

**Issue by serenamarie125** [ManageIQ/miq_v2v_ui_plugin#347]
Currently when you drill into a migration plan, you don't know if the plan is in progress/completed/migrated. 

Add a icon before the migration plan name in the breadcrumb to indicate it's status

@vconzola can you include the actual font icon names for each of the migration plan states?

**Comment by serenamarie125** [comment]
This is a stretch goal for sprint 8 if posslble

**Comment by vconzola** [comment]
Icons are: pficon-ok for Completed succesfully, pficon-error-circle-o for Completed failed (shown below), and fa-archive for Archived.
![11a-plan details copy as list in drill down - complete](https://user-images.githubusercontent.com/22823035/40510130-b6b783d8-5f69-11e8-832c-0ae28c1081d8.png)

**Comment by mturley** [comment]
Unassigning myself here until I start this (probably early tomorrow), per conversation with @serenamarie125

**Comment by mturley** [comment]
I'm on this now, @serenamarie125.

**Comment by mturley** [comment]
Build failures with #163 are distracting me, but I have started some code for this, so I'm leaving myself assigned. Hoping to knock both these issues out before Friday.

**Comment by mturley** [comment]
Ok @serenamarie125 I don't want to lose sleep over this now, my ManageIQ database is screwed up, restoring the backup is failing, and pgAdmin is crashing on me... so I can't run my code. Fresh setup in the morning should take care of it hopefully, and the work is almost done, but I suppose it's possible this stretch goal will not make the sprint-- I'll try and get this pushed through early tomorrow.

**Comment by mturley** [comment]
This will merge mid-Monday, i'm thinking.

**Comment by mturley** [comment]
@vconzola you mention here that the icons should be:

> pficon-ok for Completed succesfully, pficon-error-circle-o for Completed failed (shown below), and fa-archive for Archived.

What about for "not started"? should we do no icon, or a fourth one? and what about for "in progress"? a spinner in the breadcrumb bar maybe? Not sure if I am forgetting any states.

**Comment by vconzola** [comment]
@mturley You're correct - no icon for Not Started; spinner for In Progress. Thanks for bringing up these cases.
