### ISSUE TITLE
Inform user when a plan no longer has an associated infrastructure mapping

### ISSUE THREAD

**Issue by vconzola** [ManageIQ/miq_v2v_ui_plugin#357]
A user can delete an infrastructure mapping which has associated plans. If this happens we need to display something in the plans view informing the user that the plan's mapping is no longer available.

**Comment by serenamarie125** [comment]
@vconzola can you provide mocks asap, then we will evaluate if it can be targeted for sprint9

**Comment by vconzola** [comment]
@serenamarie125 I'll work on some mocks, but this should be a very low priority. It's the very corner of an edge case - somewhere back behind the sofa with the dust bunnies.  :-) The only time this can occur is if an infra mapping is deleted that's associated with a Not Started plan. We're already warning users that the plan will be "orphaned" if they delete the mapping, but we need some contingency in case they delete anyway. I only opened the issue because I was thinking of the specific edge case and didn't want to forget it.

**Comment by serenamarie125** [comment]
perfect!  tagging as an enhancement as well then.  Can i assume to you for now for design ?  Then once you post design you can unassign?

**Comment by vconzola** [comment]
Sure, but don't label it Sprint 9. I think playbooks and scheduling will be more than enough to keep me busy next sprint.

**Comment by michaelkro** [comment]
**Note**:  If a plan orphaned in this way will be stuck in the Not Started Plans section forever

Assuming that trying to kick off a migration plan that does not have an associated infrastructure mapping will cause an error, we'll have to at least disable the `Migrate` button.  However, kicking off a migration is the only way to move a plan from the Not Started state

**Comment by vconzola** [comment]
This one depends on infrastructure mappings being added to the migration plan list view, #496.

**Comment by vconzola** [comment]
Use same mockups as #387
