### ISSUE TITLE
Clicking delete icon causes listitem to expand/collapse

### ISSUE THREAD

**Issue by michaelkro** [ManageIQ/miq_v2v_ui_plugin#365]
Clicking the delete icon in the Overview Infra Mappings ListView causes the ListItems to expand/collapse.  This click should be isolated to the buttons and not propagate up to the containing element

**Comment by AparnaKarve** [comment]
@michaelkro Agree with you.

Also found out that `e.stopPropagation();` seems to work to resolve this.
Will get a PR out soon.

**Comment by priley86** [comment]
fixed in #366. closing.
