### ISSUE TITLE
Add Pre & Post Playbook Support to Migration Plans - Plan Wizard Changes

### ISSUE THREAD

**Issue by serenamarie125** [ManageIQ/miq_v2v_ui_plugin#368]
The user should be able to identify a pre and/or post Ansible Playbook as part of a migration plan.

Playbook Support Notes: https://docs.google.com/document/d/1dnb5RsMvVRRx4osTIeR6wTF9JXQwoNQNwW-pZsW65Ao/edit#

**Comment by serenamarie125** [comment]
@vconzola have you started this design work yet?

**Comment by vconzola** [comment]
@serenamarie125 Had meeting with Brett and others yesterday. Starting on design today.

**Comment by vconzola** [comment]
@michaelkro Here are the [mockups](https://docs.google.com/presentation/d/19CpXErM4mDsbLkx6ahQMpDn_i63eqb805GwM4M3Kl1Q/edit?usp=sharing), some of which I showed you earlier. There are still a few open questions, but this should be enough for you to get started. I will review with Brett and Marco and some of the other Mgmt UX designers tomorrow and will update the document with any changes.

@serenamarie125 @priley86 Please review when you get a chance.

**Comment by priley86** [comment]
@vconzola these mockups look good to me!

**Comment by michaelkro** [comment]
@vconzola when you have a moment, can you provide the copy for the confirm dialog?  (if a user hits next with playbook(s) selected but no VMs).  Things I need

1.  Modal Title
2.  Text Body
3.  I am assuming `warning-triangle-o` for the icon
3.  Confirm Button text
4.  I am assuming `Cancel` for secondary button text

**Comment by vconzola** [comment]
@michaelkro Here you go. Let me know if you have any questions.
![9ddd1b-createplan-playbooks selection playbooks w_ confirmation](https://user-images.githubusercontent.com/22823035/41625526-1855463e-73e7-11e8-80eb-48b942d9e43e.png)
