### ISSUE TITLE
User can cancel a migration in progress

### ISSUE THREAD

**Issue by serenamarie125** [ManageIQ/miq_v2v_ui_plugin#370]
User can cancel a migration.  Need to finalize the requirements here:
- is cancel action only enabled/available for migrations in progress
- cancel confirmation should be shown

**Comment by serenamarie125** [comment]
@bzwei do we have existing API support for this?

**Comment by serenamarie125** [comment]
Brett said it was an ask for sprint 9

**Comment by bzwei** [comment]
We don't have existing API for canceling, nor do we have backend support. It will be a feature that requires a lot of effort.

**Comment by serenamarie125** [comment]
Thanks @bzwei - FYI @bthurber if this is a need, can you chat with Greg B in priority?  Taking off our sprint9 plans

**Comment by bthurber** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1564257

**Comment by JPrause** [comment]
@miq-bot add_label blocker
Blocker to https://bugzilla.redhat.com/show_bug.cgi?id=1564257

**Comment by vconzola** [comment]
UX mockups are [here:](https://docs.google.com/presentation/d/1fVPR7RT4xC-89VLBVIYM48EIuWcOna3WqUc-em6UwMs/edit?usp=sharing)

**Comment by JPrause** [comment]
Any update on this PR. We have an upcoming build on July 10

**Comment by priley86** [comment]
Preliminary API spec for cancel from Fabien is here:
https://gist.github.com/fdupont-redhat/197fb71adf48482974b794a8a261de34

We can start prototyping this next...

**Comment by mturley** [comment]
Starting on this while I wait for review on #467 to wrap up #399 .

**Comment by mturley** [comment]
My PR for this will go out today. I dropped the ball on finishing #399 this sprint because it needs another API call. But this I can have done today.

**Comment by mturley** [comment]
@JPrause sorry for the delay. The backend PR for this issue is now merged. The frontend PR will be up shortly and merged early next week.

**Comment by bzwei** [comment]
@mturley please use this API call https://github.com/ManageIQ/manageiq-api/pull/421

**Comment by mturley** [comment]
Sounds good, thanks @bzwei. This is my top priority today

**Comment by mturley** [comment]
This will now be done in https://github.com/ManageIQ/miq_v2v_ui_plugin/issues/511, my original entire-plan cancel PR was, well, cancelled.
