### ISSUE TITLE
Investigate how to debug QEs environment

### ISSUE THREAD

**Issue by serenamarie125** [ManageIQ/miq_v2v_ui_plugin#372]

**Comment by mturley** [comment]
@vconzola mentioned that this might be a good follow up for me after #353, so just leaving this comment here as a reminder 🎗

**Comment by mturley** [comment]
@serenamarie125 is there any more information you can give me on the context around this issue? Is there a particular problem with their environment we wanted to debug, or is this just a general call for "figure out how to do remote debugging"?

**Comment by serenamarie125** [comment]
@mturley - this was added per request of @priley86 , maybe he can shed some light, or @vconzola ?

**Comment by vconzola** [comment]
@mturley Yeah, I think we can put this one on the shelf for a bit. Good thing for you to noodle on when you've got free time, but not high priority. Part of the the larger "How do we make our process/tools better so we're not dependent on other teams problem."

**Comment by priley86** [comment]
would you be OK w/ closing this issue @vconzola ?

I think what @mturley is proposing is fine for helping us spoof API data on our local machine. I filed a few more issues yesterday which are somewhat related and should help when we get around to them.

https://github.com/ManageIQ/miq_v2v_ui_plugin/issues/373#issuecomment-398738270

I think once @AparnaKarve gets around to #423 we should revisit this and see if that suffices for now.  I'm going to continue looking at #424 as I have time (hopefully will get this to a W.I.P. state early next week).

**Comment by vconzola** [comment]
@priley86 Sure, go ahead and close it if the work is done and/or being continued in #423 and #424.
