### ISSUE TITLE
Investigate nightly build issues

### ISSUE THREAD

**Issue by serenamarie125** [ManageIQ/miq_v2v_ui_plugin#373]
investigate nightly build scripts & QE production build versus our dev build

**Comment by priley86** [comment]
Going to start taking a look at this and gathering what I can...

**Comment by vconzola** [comment]
Nightly build issues are being investigated by @bthurber and the QE team. No need to involve UI Dev.

**Comment by priley86** [comment]
While we aren't reviewing the QE scripts directly, it may behove us to continue in sync w/ the appliance build scripts located here and find opportunities for logging v2v specific build configurations:
https://github.com/ManageIQ/manageiq-appliance-build

I've filed #422 , #423 , and #424 after discussing some further options yesterday around UI reliability. Beyond this, we will have to do some more environment specific investigations it sounds...
