### ISSUE TITLE
Allow access to Migrations section when there are no Infrastructure Mappings

### ISSUE THREAD

**Issue by michaelkro** [ManageIQ/miq_v2v_ui_plugin#387]
Before we added the feature to allow deletion of infrastructure mappings, it was not possible for there to exist migrations in any state (complete, in progress, not started) if there were no saved mappings.  Thus the current implementation hides the Migrations section until an infrastructure mapping is created.

The ability to delete mappings allows for the following scenario (assuming a fresh environment for simplicity)

1. Create an infrastructure mapping
2. Create and execute one or more migration plans using the mapping
3. Delete the mapping
4. Notice that the aggregate cards indicate that there exist migration plans, but there is no way for the user to access them

### Screenshot
![fullscreen_6_4_18__8_44_am](https://user-images.githubusercontent.com/15141412/40918189-942f8c44-67d3-11e8-8b96-351b9b285d32.png)

**Comment by vconzola** [comment]
@michaelkro Good catch. Yet another edge case to consider when mappings are deleted (see also #357), but not high priority, I think.

**Comment by vconzola** [comment]
@michaelkro I'm guessing what's happening is that the UI logic says to display the mappings empty state anytime there are no mappings. For now, let's change the logic for the mappings empty state so that it is displayed when there are (no mappings AND no plans). If at least one plan exists then we'll need to display a different empty state similar to the empty state for plans that's displayed when a mapping exists, but there are no plans yet. I'll do a mockup.

**Comment by vconzola** [comment]
Design notes:
1. If there are any plans in progress, disable the delete mappings button for all mappings (we might be doing this already) If not, this is probably a separate issue.

2. For not started plans, display a warning in place of the infra mapping name and disable the Migrate button.
![overview no mapping not started](https://user-images.githubusercontent.com/22823035/43102067-1c0e7694-8e98-11e8-8c53-725fe045e8e2.png)

3. For completed plans, display a warning in place of the infra mapping name and disable the Retry button.
![overview no mapping completed](https://user-images.githubusercontent.com/22823035/43102090-267a4fb8-8e98-11e8-844f-cd193c57b589.png)
