### ISSUE TITLE
[Test Automation Requirement] Please add an id or a name to div surrounding the Infrastructure Mappings List

### ISSUE THREAD

**Issue by kedark3** [ManageIQ/miq_v2v_ui_plugin#394]
See this screen shot for proposed id and the div where it should be
![screenshot from 2018-06-06 10-01-11](https://user-images.githubusercontent.com/8180469/41042857-abe1f716-6970-11e8-8759-77c9df127697.png)

**Comment by kedark3** [comment]
@priley86 we may need some more identifiers in here: 
![screenshot from 2018-06-06 12-39-32](https://user-images.githubusercontent.com/8180469/41052432-be50eb26-6986-11e8-8fed-53307b924ef4.png)
Most of the items have only class "row-sm-4" or "col-sm-4" which makes it harder to tell which is which in automation.

**Comment by priley86** [comment]
the original issue should now be resolved. I would suggest a new issue for any other related automation in the expansion below (since that UI was changed recently). hope this makes sense!
