### ISSUE TITLE
Take screenshots of all V2V screens to be used for "copy" review

### ISSUE THREAD

**Issue by serenamarie125** [ManageIQ/miq_v2v_ui_plugin#396]
Take screenshots of all V2V screens (including notifications and message dialogs) and put them into this drive: https://drive.google.com/drive/folders/1pqBQDtszojXJOnXHYaZ3V7QkKY0xax1d

**Comment by priley86** [comment]
Sent all screenshots to Stacy - will create additional issues after review.
