### ISSUE TITLE
Pre & Post Playbook Support  - Overview Page Changes

### ISSUE THREAD

**Issue by vconzola** [ManageIQ/miq_v2v_ui_plugin#399]
This issue is for changes needed to the Overview page of the UI to support pre- and post-migration playbooks.

**Comment by vconzola** [comment]
Mockups [here](https://docs.google.com/presentation/d/19CpXErM4mDsbLkx6ahQMpDn_i63eqb805GwM4M3Kl1Q/edit?usp=sharing).

I think the biggest part of this one will be the logic required to change between states in the status cards - pre-migration, migration, post-migration and updating the (error) counts as appropriate. There's really no new UI display change required.

**Comment by mturley** [comment]
Taking a look at this next. @vconzola do you know if the API is in progress for this, or if I should poke someone?

**Comment by vconzola** [comment]
@mturley API should be in progress. I'll try to get an update tomorrow morning in Brett's stand-up.

**Comment by mturley** [comment]
Cool, thanks!

**Comment by mturley** [comment]
I was splitting time with that API tampering tool, but now I'm focused on just this until it's done.

**Comment by JPrause** [comment]
@miq-bot add_label blocker
This is a blocker to: https://bugzilla.redhat.com/show_bug.cgi?id=1564250

**Comment by AllenBW** [comment]
allenbot at yer service

**Comment by JPrause** [comment]
Any update on this PR. We have an upcoming build on July 10

**Comment by vconzola** [comment]
@JPrause PR for the Overview UI changes should be up today, but still waiting on backend support for all of the playbook related issues.

**Comment by mturley** [comment]
@vconzola just wrapping up my weekend catch-up time, I left a few notes on what is left for this issue in my PR #467. Really, I think I'm done so I'm going to move on, but I need to coordinate with @michaelkro to combine with his PR, and we may need one more revision when we test with real APIs.

I'm moving onto the next issue now (so, Monday morning). Was my plan for Friday afternoon originally, but I'm getting caught up here.

**Comment by michaelkro** [comment]
https://github.com/ManageIQ/manageiq-content/pull/355
