### ISSUE TITLE
Pre & Post Playbook Support - Plan Details Page Changes

### ISSUE THREAD

**Issue by vconzola** [ManageIQ/miq_v2v_ui_plugin#400]
This issue is for the changes needed to the Details page to support pre- and post-migration playbooks.

**Comment by vconzola** [comment]
Mockups [here](https://docs.google.com/presentation/d/19CpXErM4mDsbLkx6ahQMpDn_i63eqb805GwM4M3Kl1Q/edit?usp=sharing).

**Comment by JPrause** [comment]
@miq-bot add_label blocker
This is a blocker to: https://bugzilla.redhat.com/show_bug.cgi?id=1564250

**Comment by JPrause** [comment]
Any update on this PR. We have an upcoming build on July 10

**Comment by michaelkro** [comment]
https://github.com/ManageIQ/manageiq-content/pull/355
