### ISSUE TITLE
Icons actions should be wrapped with Buttons

### ISSUE THREAD

**Issue by priley86** [ManageIQ/miq_v2v_ui_plugin#402]
When hovering the delete action for an infrastructure mapping, the cursor should change to the `pointer` style (default for Buttons). Wrapping the icon with a Button element styled as "link" style will give the correct default PatternFly behavior.

This can be seen on the "button link" samples here (far right):
https://rawgit.com/patternfly/patternfly/master-dist/dist/tests/buttons.html

**Comment by AllenBW** [comment]
looks like github isn't closing... 🤦‍♀️
