### ISSUE TITLE
Consistent DOM rquirements for QE Automation

### ISSUE THREAD

**Issue by kedark3** [ManageIQ/miq_v2v_ui_plugin#414]
![screenshot from 2018-06-14 14-18-30](https://user-images.githubusercontent.com/8180469/41430434-fcbd5ec8-6fdd-11e8-986a-a436d7b7d8fa.png)
Look at the highlighted `div` with class `infra-mapping-item-source`, 
for each item in the list there, there is a div surrounding it.
![screenshot from 2018-06-14 14-19-25](https://user-images.githubusercontent.com/8180469/41430433-fc982860-6fdd-11e8-94cf-3ba8c31b32ad.png)

Look at the highlighted `div` with class `infra-mapping-item-target`, 
for each item in the list there, there is NO a div surrounding it.

**Request**: We should have div for each list item in `infra-mapping-item-target`

**Reason:** It will help QE to automate this effectively as putting each item in this list of targets will allow us to use as a delimiter while reading it in our code.

**Comment by priley86** [comment]
Hey @kedark3 - i think this is achievable. I should be able to wrap each individual target within a div if that helps you.

Thanks for reaching out.

**Comment by priley86** [comment]
Actually - on further review, this is working as intended. Each target will get it's own `div` with class `infra-mapping-item-target`. It may be confusing, but that is actually the full name "{data center} \ {provider name} {cluster name} \ {network name}". The network name is rendered in a separate string, but those are actually associated. In your example, that is a single target network in its own `div` (not sure why the cluster name and the data center are both "Default", but that appears to be the case). 

So for that reason, I think this should be closed.

Are you OK w/ this after the explanation @kedark3 ?

**Comment by kedark3** [comment]
@priley86 yes, I agree, thinking from functionality POV, there will be only one item under each `infra-mapping-item-target` so we can close this.
