### ISSUE TITLE
UI/API schema checks 

### ISSUE THREAD

**Issue by priley86** [ManageIQ/miq_v2v_ui_plugin#424]
In this issue, we will look at API schema validation once the JSON responses have been parsed by the UI. If schema checks fail and attributes are missing that are expected from the current UI build, we will log a schema failure to the console. This should help UI developers analyzing QE issues.

**Comment by priley86** [comment]
Going to start investigating this...

**Comment by priley86** [comment]
going to continue moving here and try to have some things ready for test mid next week.

**Comment by AllenBW** [comment]
Pr merged, we can now close this (remember to use yer github hooks 😏 )

**Comment by priley86** [comment]
thanks - yea... i will probably open up some more issues as I have time to work on adding more validation, but I'm fine w/ closing this initial issue now!

**Comment by AllenBW** [comment]
Future issue, can be schema *enhancement* 😏 😋
