### ISSUE TITLE
Remove product->transformation setting

### ISSUE THREAD

**Issue by Fryguy** [ManageIQ/miq_v2v_ui_plugin#432]
The product-> transformation setting in settings.yml is a toggle for disabling the feature while still dev-incomplete.  On master, this is no longer the case, so we should remove this flag, as we don't keep these extra product settings for officially released features.  We can wait until backporting dies down a bit in order to avoid backport issues.

cc @himdel @martinpovolny

**Comment by Fryguy** [comment]
Depends on #417 , as RBAC will be the proper way to disable the feature for users.

**Comment by priley86** [comment]
it looks like [417](https://github.com/ManageIQ/miq_v2v_ui_plugin/pull/417) has been merged. Can you describe any additional work here @Fryguy ?

**Comment by himdel** [comment]
@priley86 The remaining work is just removing these:

```
manageiq/config/settings.yml
979:  :transformation: true
```

and 

```
lib/manageiq/v2v/engine.rb
15:        ::Settings.product.transformation == true ? Menu::Item.new('migration', N_('Migration'), 'migration', {:feature => 'migration', :any => true}, '/migration', :default, :compute) : nil

config/routes.rb
2:if ::Settings.product.transformation == true
```
