### ISSUE TITLE
All VMs don't show on Migration Plan Request Details Page

### ISSUE THREAD

**Issue by kedark3** [ManageIQ/miq_v2v_ui_plugin#437]
See https://bugzilla.redhat.com/show_bug.cgi?id=1594428 for more description

**Comment by priley86** [comment]
@AparnaKarve is fixing this in #374 this sprint.

**Comment by AllenBW** [comment]
@JPrause a dupe of which bz?

**Comment by JPrause** [comment]
@AllenBW see @priley86 comment above.

**Comment by AllenBW** [comment]
@JPrause yah, not seeing another bz # 🤷‍♂️

**Comment by JPrause** [comment]
Any update on this PR. We have an upcoming build on July 10

**Comment by AparnaKarve** [comment]
@JPrause Work is in progress, a PR should be out soon, sometime this week.

**Comment by vconzola** [comment]
Duplicate of #374.
