### ISSUE TITLE
Description of migration plan should be wrapped, not float over VM Count 

### ISSUE THREAD

**Issue by AllenBW** [ManageIQ/miq_v2v_ui_plugin#448]
https://bugzilla.redhat.com/show_bug.cgi?id=1596286

![screenshot from 2018-06-28 10-14-37 1](https://user-images.githubusercontent.com/6640236/42040571-f4d88314-7abd-11e8-822b-76e5aee80f5c.png)

😭 🌮

**Comment by AllenBW** [comment]
<img width="803" alt="screen shot 2018-06-28 at 10 39 03 am" src="https://user-images.githubusercontent.com/6640236/42041247-8353f906-7abf-11e8-83b8-0ced4e8d7e82.png">
OH YAHHHH

**Comment by priley86** [comment]
Cool - we have a component for this...`EllipsisWithTooltip`... thanks for reporting!

**Comment by AllenBW** [comment]
yah I added it 😆
