### ISSUE TITLE
Duplicate Plan Names

### ISSUE THREAD

**Issue by priley86** [ManageIQ/miq_v2v_ui_plugin#451]
I know the term "duplicate" is starting to make us shriek...

Per our last email on this subject - we would like to use the UI to work around the duplicate plan name issue in the short term by simply checking the service template (plans) in memory (loaded from Overview) and passing them into the Plan Wizard (to allow checking for duplicates). This is a short term fix - the long term fix is obviously adding this validation on the backend.

Would like to resolve this for 5.9.4.

BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1567225

**Comment by priley86** [comment]
Adding this to Sprint 10.

**Comment by priley86** [comment]
Looks like it's still up for grabs... going to grab this one next 🤹‍♂️

**Comment by agrare** [comment]
@priley86 backend support for name uniqueness validation within a tenant was merged https://github.com/ManageIQ/manageiq/pull/17677
