### ISSUE TITLE
Update Plan Wizard Final Step Error State

### ISSUE THREAD

**Issue by michaelkro** [ManageIQ/miq_v2v_ui_plugin#466]
Currently, if there is a problem with plan creation, the final step of the Plan Wizard shows an error screen

<img width="1920" alt="fullscreen_7_3_18__9_38_am" src="https://user-images.githubusercontent.com/15141412/42223078-e587a77e-7ea4-11e8-8a5b-de90a0a7fe1d.png">

However, the `retry` button does not do anything.  We'd like to update this screen to

1. Replace the generic error messaging with what is returned from the API
  
    <img width="713" alt="devtools_-_localhost_8080_migration" src="https://user-images.githubusercontent.com/15141412/42223282-676d603a-7ea5-11e8-8435-d1220d7f86a1.png">

2. Turn the `retry` button to a `close` button that returns the user to Overview

**Comment by priley86** [comment]
I noted when fixing #451 that the backend will now return a specific error message when the plan name is existing. Do we want to show a specific error message for this or leave it generic?

Here's what that response looks like:
```
{"error":{"kind":"bad_request","message":"Could not create Service Template - Validation failed: Name has already been taken","klass":"Api::BadRequestError"}}
```

**Comment by mturley** [comment]
I'm on this next, and then #532.

**Comment by Yadnyawalkya** [comment]
**Internal tracking**  
https://bugzilla.redhat.com/show_bug.cgi?id=1613041
