### ISSUE TITLE
Progress bar for Retried migration is not updating 

### ISSUE THREAD

**Issue by kedark3** [ManageIQ/miq_v2v_ui_plugin#469]
https://bugzilla.redhat.com/show_bug.cgi?id=1596732

@AparnaKarve this is created as Brett requested me to.

**Comment by AparnaKarve** [comment]
@kedark3 #468 is now merged.
Can you verify it with the latest nightly? Thanks.

**Comment by kedark3** [comment]
@AparnaKarve UPDATE1: In the latest nightly of 10th July, I failed 2 different migrations and retired, and saw that the progress bar did work. Now going to try combination of one failed and one succeeded migration and retry that. 
Will post UPDATE2 in some time.

**Comment by kedark3** [comment]
For the MIQ Nightly built on July 10th, I ran one plan, which had 3 VMs, 1 Success, 2 Failed. Then retried the Plan. All VMs migrated correctly and all information on Migration Dashboard and details page is correct. 
![screenshot from 2018-07-11 14-50-33](https://user-images.githubusercontent.com/8180469/42593402-4c1c74d0-851a-11e8-9f27-0787148e4ae0.png)

**Comment by AparnaKarve** [comment]
@kedark3 Thank you very much for the detailed testing. Really appreciated!

Based on your positive testing results, I am going to go ahead and close this issue.
Thanks.

**Comment by priley86** [comment]
Nice job @kedark3 & @AparnaKarve 👏
