### ISSUE TITLE
Cannot create Migration Plan

### ISSUE THREAD

**Issue by kedark3** [ManageIQ/miq_v2v_ui_plugin#471]
https://bugzilla.redhat.com/show_bug.cgi?id=1598881
![screenshot from 2018-07-06 13-45-18](https://user-images.githubusercontent.com/8180469/42393192-9577d098-8123-11e8-8f04-5b7afc09afe1.png)

**Comment by AparnaKarve** [comment]
@lfu @bzwei This PR https://github.com/ManageIQ/manageiq/pull/17627 seems to be causing the above breakage. Can you please take a look? Thanks.
