### ISSUE TITLE
Create Plans empty state / archived plans

### ISSUE THREAD

**Issue by priley86** [ManageIQ/miq_v2v_ui_plugin#475]
I noted recently in #451 that while Overview screen is showing, and only Archived Plans exist, we show the "Create Migration Plan" empty state button (w/o the Archived Plans filter available). We should probably instead show the empty states for Not Started / In Progress/ Completed plans and the list of Archived plans instead. *Note*: this involves waiting for load of Archived plans in Overview to determine if we should show the empty state view or not.

thoughts @vconzola ?

**Comment by vconzola** [comment]
@priley86 I don't see anything about this in #451. Please add a screenshot.

**Comment by priley86** [comment]
@vconzola - this is an unrelated bug I stumbled upon while working that one...the issue is - the user is unable to access Archived Plans when no Not Started/In Progress/Completed plans exist (for some reason we are showing the initial empty state in that scenario). I think this should be changed.

**Comment by priley86** [comment]
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1600902

**Comment by bthurber** [comment]
Fixes  https://bugzilla.redhat.com/show_bug.cgi?id=1600902
