### ISSUE TITLE
Migration from CSV file fails the second time

### ISSUE THREAD

**Issue by bthurber** [ManageIQ/miq_v2v_ui_plugin#481]
Steps to Reproduce:
1. Migrate a VM using the list option (to select from discovered VM's).
2. Migrate the same VM using CSV file, with content:
Name
<vm_name>
..
3. Try step 2 again.

Actual results:
Error.

![selection of vm from csv](https://user-images.githubusercontent.com/4692674/42530588-38c2d9fc-8447-11e8-9935-bf13ef660cef.png)

**Comment by bthurber** [comment]
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1597977

**Comment by bzwei** [comment]
@priley86 see my comment in the BZ. May not be a bug.

**Comment by bthurber** [comment]
@bzwei @priley86 @AparnaKarve can the team review and advise on the issue?  If it's not a bug is this behavior as expected or is this user error?

**Comment by priley86** [comment]
My guess is we can show a more detailed error message as an enhancement? It does seem to be a user error that's unintended. 

@bzwei can you confirm that the backend does not intend to change the response to the UI in these scenarios? I think that the UI should reflect accordingly. Do you have a suggestion w/ regards to what error messaging we should display?

**Comment by AparnaKarve** [comment]
Minutes ago, @kedark3 and I were discussing a related issue brought up by someone in the rhv team...

They had 2 source networks with id's `2` and `3` mapped to a target network id `14`.
A closer look at all the available LANS revealed that the target network `14` was missing.

An Infrastructure Mapping with missing infrastructure resources (clusters, datastores, networks), like in the above case,  is basically useless -- if possible we should show an error/warning for an invalid infrastructure mapping.

So yeah, agree with @priley86 's suggestion above.

**Comment by bzwei** [comment]
@fdupont-redhat 
The log quoted in the BZ
```
----] E, [2018-07-04T08:09:31.256725 #8906:3c20300] ERROR -- : Method STDERR: (druby://127.0.0.1:33075) /opt/rh/cfme-gemset/bundler/gems/cfme-automation_engine-ec1e41d2b579/lib/miq_automation_engine/service_models/miq_ae_service_service_template_transformation_plan_task.rb:8:in `block in transformation_destination': undefined method `object_class' for nil:NilClass (NoMethodError)
```
The nil object is actually the [source_obj](https://github.com/ManageIQ/manageiq-automation_engine/blob/master/lib/miq_automation_engine/service_models/miq_ae_service_service_template_transformation_plan_task.rb#L10). Please investigate how it can happen, specially at the second attempt to migrate.

**Comment by kedark3** [comment]
I would like to say that this is not CSV issue, I made sure of testing this again and I could get my migration to work correctly and successfully.

**Comment by bthurber** [comment]
@kedark3 positive it is not a .csv issue.  I renamed the BZ to reflect the problem more accurately.  This issue can be closed as the problem was realted to the environment and method of cleaning it.
