### ISSUE TITLE
Calendar/Clock selection box needs to remain cleaner on browser resize

### ISSUE THREAD

**Issue by kedark3** [ManageIQ/miq_v2v_ui_plugin#498]
https://bugzilla.redhat.com/show_bug.cgi?id=1602792
![screenshot from 2018-07-18 09-54-28](https://user-images.githubusercontent.com/8180469/42886420-856af34a-8a71-11e8-86b1-1f121ac96835.png)

**Comment by AllenBW** [comment]
This isn't something we control, 's patternfly styling thing, I might be able to hunt it down and fix it up eventually, but gonna hit this with lowest of low priorities..

(alternatively yah might want to open a pr here: https://github.com/patternfly/patternfly)

Oh yeah to see it "broken" at the source...
https://rawgit.com/patternfly/patternfly/master-dist/dist/tests/date-and-time.html#

**Comment by priley86** [comment]
Ya, I agree. Would be nice to file an upstream issue in PF about this. Thanks @AllenBW.

**Comment by vconzola** [comment]
To be fixed by PatternFly.

**Comment by bthurber** [comment]
@vconzola can you provide some detail on when/how this will be resolved?

**Comment by AllenBW** [comment]
@bthurber its outta our hands, see the patternfly/patternfly issue opened here: https://github.com/patternfly/patternfly/issues/1096 Looks like the issue was added to nexttodo 🤷‍♂️
