### ISSUE TITLE
V2V Migration UI becomes unusable on provider add-remove-add

### ISSUE THREAD

**Issue by kedark3** [ManageIQ/miq_v2v_ui_plugin#499]
https://bugzilla.redhat.com/show_bug.cgi?id=1602796
![screenshot from 2018-07-18 10-09-52](https://user-images.githubusercontent.com/8180469/42886942-cfe63834-8a72-11e8-8bb8-8f832a7c923b.png)

**Comment by priley86** [comment]
thanks @kedark3 - i will start working on a fix today.

**Comment by kedark3** [comment]
5.9.4.1 is still broken,https://bugzilla.redhat.com/show_bug.cgi?id=1602796#c9

Although, 5.10.0.6 is showing correctly as mentioned in #503 (comment)
