### ISSUE TITLE
Add editable cells to React tables

### ISSUE THREAD

**Issue by vconzola** [ManageIQ/miq_v2v_ui_plugin#532]
Refer to https://www.patternfly.org/pattern-library/forms-and-controls/inline-edit/#inline-edit-in-a-table-view

**Comment by mturley** [comment]
I'm starting this after I finish #466.

**Comment by jeperry** [comment]
[Editable cells in table ](https://rawgit.com/patternfly/patternfly-react/gh-pages/index.html?selectedKind=patternfly-react%2FContent%20Views%2FTable%20View&selectedStory=Table%20With%20Inline%20Edit%20Row&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs)seems to already exist in React - what is the difference here?

**Comment by mturley** [comment]
Closing this because we already have this behavior in React as @jeperry points out. Usage of it will start in #546.
