### ISSUE TITLE
500 Internal Server Error while scheduling migration plan

### ISSUE THREAD

**Issue by Yadnyawalkya** [ManageIQ/miq_v2v_ui_plugin#542]
**Description of problem**
500 Internal Server Error while scheduling migration plan

**Version-Release**
5.9.4.2.20180802030318_f91df08 

**How reproducible**
100%

**Steps to Reproduce**
1. Create plan
2. Scheduled plan (pick date + time)
(You will get pop with error)

**Actual results**
Getting error pop-ups.

**Expected results**
Should not get that.

**Additional info**
Also found on 5.10.0.8

**Internal tracking**
https://bugzilla.redhat.com/show_bug.cgi?id=1612112

**Comment by AllenBW** [comment]
@Yadnyawalkya soooo this bug... still reproducible?  🤔

**Comment by AllenBW** [comment]
Closing cuz... its not reproducible.
