### ISSUE TITLE
UX for migration cancel is misleading

### ISSUE THREAD

**Issue by vconzola** [ManageIQ/miq_v2v_ui_plugin#548]
The following changes should be made to the plan details page when a migration is cancelled:
1. The text for the notification should read, "Migration cancel request submitted for _vm_name_".
2. The migration status when a cancel is in process should be "Cancelling migration". The counter should continue counting and the spinner icon should keep spinning (don't change).
4. When the cancel is successful the icon should change to fa-ban and the status should say "Migration cancelled".
5. If the cancel fails for some reason (Do we get a fail notification?) we should display a failed notification saying, "Migration cancel request failed for _vm_name_".

**Comment by AparnaKarve** [comment]
> When the cancel is successful the icon should change to fa-ban and the status should say "Migration cancelled".

> If the cancel fails for some reason (Do we get a fail notification?) we should display a failed notification saying, "Migration cancel request failed for vm_name".

There is no specific indication from the backend if the Cancel operation was successful or not.
I suppose I can just display "Migration cancelled" when the cancelled task completes.
(A cancelled task usually completes with a `VM migration failed` status)

**Comment by vconzola** [comment]
@AparnaKarve So does that mean if we get a "VM migration failed" status we really don't know if the migration failed or was cancelled? We just have to assume based on the time between when the cancel request is sent and the fail status comes back that it's a cancel and not a fail? Yuck. Do we set the cancel_requested flag or does the backend?

**Comment by AparnaKarve** [comment]
@vconzola This is how I can describe the lifecycle of `Cancel` (the way I know it) --

- When the user hits Cancel for a task, we send an API POST request on the task with `action=cancel`
- The return of this API request could be a success or a failure (like any other API requests)
- If it's a success, the backend marks this task with `cancel_requested=true`. The back-backend processes (Fabien's automate code)  then transition the task from `migration` -> `cancelling migration`
- In a couple of seconds (or a couple of polling rounds), the task completes with a `VM migration failed` status

So based on this info, the UI can draw a logical conclusion that a task has completed it's cancellation operation by looking at `cancel_requested=true` and `status='VM migrtion failed'`

**Comment by vconzola** [comment]
@AparnaKarve Got it. As long as the migration doesn't fail between cancel_requested=true and status='VM migration failed' that should be accurate. and i guess it doesn't really matter in the end. either way it's a "failed" migration and will have to be retried.
