### ISSUE TITLE
Next button is not enabled by default while selecting valid VMs by default on CSV import

### ISSUE THREAD

**Issue by Yadnyawalkya** [ManageIQ/miq_v2v_ui_plugin#558]
**Issue**
On valid vm imports, vms getting selected automatically but `Next` button still not get enable by default (which is I guess should be enable by default since vm selection is already done). 

Currently to enable `Next` button we have to double-check any selected vm checkbox which is somehow weird additional thing

**Behavior**
![](https://user-images.githubusercontent.com/811963/43225878-45440e3e-9028-11e8-98c0-90b26cc851b1.gif)

**Internal tracking** - https://bugzilla.redhat.com/show_bug.cgi?id=1610393
**Related PR** - https://github.com/ManageIQ/miq_v2v_ui_plugin/pull/516

**Comment by priley86** [comment]
Gonna grab this one real quick....

**Comment by priley86** [comment]
heh ;) - looks like there is no work at all here. This is working as designed @Yadnyawalkya . See:

https://github.com/ManageIQ/miq_v2v_ui_plugin/pull/516
https://github.com/ManageIQ/miq_v2v_ui_plugin/issues/240

I believe this was decided in previous meetings/discussions. Are you ok w/ closing this issue?

**Comment by Yadnyawalkya** [comment]
@vconzola can you confirm this usecase here? I think double-clicking vms in table is additional weird thing to do, what say?
For context refer this bz https://bugzilla.redhat.com/show_bug.cgi?id=1610393#c3

**Comment by Yadnyawalkya** [comment]
Thank you everyone! \o/ :+1:  :1st_place_medal: :
