### ISSUE TITLE
Error if target compute fetch returns no records

### ISSUE THREAD

**Issue by michaelkro** [ManageIQ/miq_v2v_ui_plugin#560]
After fetching all the target clusters/cloud_tenants, we are making an additional call to the `hosts` endpoint in order to determine whether or not conversion hosts have been configured.  This call will fail if nothing is returned from the initial query

Steps to Reproduce:
1.  Delete all instances of `EmsCluster` with `ext_management_system.emstype=rhevm`
2.  Visit the clusters step in the mapping wizard

![manageiq__migration](https://user-images.githubusercontent.com/15141412/43916703-52d68832-9bdc-11e8-99db-87964037f970.png)

**Comment by mturley** [comment]
Dang, good catch @michaelkro. I suppose that's a bug in my change from earlier this week, let me know if you want me to look at it with you.
